steps:
  # 1. Build the Reactive Engine Container
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/reactive-engine', '.']

  # 2. Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/reactive-engine']

  # 3. Deploy to Cloud Run (The Antigravity Core)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'antigravity-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/reactive-engine'
      - '--region'
      - 'asia-southeast1' # Singapore Latency Optimization
      - '--allow-unauthenticated'
      - '--min-instances'
      - '1' # Warm Pool: Mitigate Cold Starts

  # 4. Deploy Backend (The Recursive Engine)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd functions && \
        npm install && \
        gcloud functions deploy antigravity-engine \
          --gen2 \
          --region=asia-southeast1 \
          --runtime=nodejs22 \
          --source=. \
          --entry-point=onIntentCreated \
          --trigger-event-filters=type=google.cloud.firestore.document.v1.created \
          --trigger-event-filters=database='(default)' \
          --trigger-event-filters=document='Latent_Events/{eventId}'

images:
  - 'gcr.io/$PROJECT_ID/reactive-engine'
